version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - 5672:5672       # AMQP
      - 1884:1883       # MQTT
      - 15672:15672     # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
#      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    command: >
      bash -c "
        rabbitmq-plugins enable --offline rabbitmq_management rabbitmq_mqtt &&
        rabbitmq-server
      "

volumes:
  rabbitmq-data:
